package edu.northeastern.cs6510.selfcheckout.analytics;
import edu.northeastern.cs6510.selfcheckout.api.ApiException; import edu.northeastern.cs6510.selfcheckout.catalog.CatalogService; import edu.northeastern.cs6510.selfcheckout.config.SelfCheckoutProperties; import java.time.Instant; import java.util.*; import java.util.concurrent.atomic.AtomicLong; import org.springframework.stereotype.Service;
@Service public class AnalyticsService {
 private final AtomicLong sequence=new AtomicLong(); private final String[] ring; private final SelfCheckoutProperties p; private final CatalogService catalog; private volatile PopularityWindow snapshot;
 public AnalyticsService(SelfCheckoutProperties p,CatalogService catalog){this.p=p;this.catalog=catalog;ring=new String[p.windowSize()];snapshot=new PopularityWindow(p.windowSize(),p.slideInterval(),0,0,Instant.now(),List.of());}
 public synchronized void recordScan(String sku){long n=sequence.incrementAndGet();ring[(int)((n-1)%ring.length)]=sku;if(n>=p.windowSize()&&(n-p.windowSize())%p.slideInterval()==0) publish(n);}
 private void publish(long end){Map<String,Integer> counts=new HashMap<>();for(String sku:ring)if(sku!=null)counts.merge(sku,1,Integer::sum);var items=counts.entrySet().stream().sorted(Map.Entry.<String,Integer>comparingByValue().reversed().thenComparing(Map.Entry.comparingByKey())).map(e->new PopularItem(e.getKey(),catalog.findBySku(e.getKey()).map(x->x.name()).orElse(e.getKey()),e.getValue(),0)).toList();var ranked=new ArrayList<PopularItem>();for(int i=0;i<items.size();i++){var x=items.get(i);ranked.add(new PopularItem(x.sku(),x.name(),x.scanCount(),i+1));}snapshot=new PopularityWindow(p.windowSize(),p.slideInterval(),end-p.windowSize()+1,end,Instant.now(),List.copyOf(ranked));}
 public PopularityWindow current(int limit){if(limit<1)throw ApiException.invalidLimit();var s=snapshot;return new PopularityWindow(s.windowSize(),s.slideInterval(),s.windowStart(),s.windowEnd(),s.computedAt(),s.items().stream().limit(limit).toList());}
}
